#+TITLE: git

* git拉取某个版本的某个文件，存成一个新的名称
  很多时候，我们需要把某个版本的文件拉取出来作为参照，但是又不能覆盖现有的版本。
  [[https://stackoverflow.com/questions/888414/git-checkout-older-revision-of-a-file-under-a-new-name][方法]]：
  #+BEGIN_SRC bash
  $ git show d2ade3fd:./xxx.js > xxx_old.js # d2ade3fd是版本号
  #+END_SRC

* <pathspec> -- path special
  git有很多命令可以指定=文件的作用范围=。=pathspec=大概就是这样的东西。它的格式几乎跟linux的路径语法是一致的，下面结合例子来对它有个感性认知。

  1. 相对路径:
     #+BEGIN_SRC bash
     $ git rm -- ./a.txt             # git rm当前目录的a.txt
     #+END_SRC

  2. 绝对路径:
     这里是的=根目录=指的是=git仓库根目录=。

     #+BEGIN_SRC bash
     $ git rm -- :/a.txt             # git rm掉仓库根目录下的a.txt
     #+END_SRC
  
  3. 集合路径:

     #+BEGIN_SRC bash
     $ git rm -- :/{a,b,c}/k.txt     # git rm掉/a/k.txt, /b/k.txt, /c/k.txt这三个文件 
     #+END_SRC

     注意：集合里的逗号前后不能有空格。 ~{a, b, c}~这种写法会无法通过。这个语法跟很多linux的命令是一致的，比如~ls {dirA,dirB}~。

  4. 通配符:
     这也是必不可少的。
     #+BEGIN_SRC bash
     $ git rm -- *.json              # git rm掉当前目录下所有以json为后缀名的子文件
     #+END_SRC

  5. 组合多个=pathspec=
     用引号包住=pathspec=，用=空格= 隔离多个=pathspec=就可以了。
     #+BEGIN_SRC bash
     $ git rm -- '*.json' ':./a.txt' 
     #+END_SRC

  6. 更多的东西
     =pathspec= 还支持类似：“排除某个文件夹”(~:(exclude)/path/to/exclude~)，“某个文件夹的所有文件”(~:/dira/**~)等等之类的操作。更多内容见[[https://git-scm.com/docs/gitglossary#gitglossary-aiddefpathspecapathspec][pathspec]]。

   
  =pathspec=大概就这几种格式。有很多命令可以使用=pathspec=，add、rm、log、grep、clean、checkout、ls-files。接下来我们举几个比较有用的实战例子。

** 显示某个文件的历史commit
   :PROPERTIES:
   :ALIAS:    git list history commit for a special file
   :END:

   直接给 ~git log~ 指定一个 =pathspec= 到这个文件就可以了。

   #+BEGIN_SRC bash
   $ git log -- ./a.txt
   #+END_SRC

** 更加精确的git grep
   :PROPERTIES:
   :ALIAS:    git grep special file type or exclude special dir path
   :END:
   很多时候，对整个git项目进行~git grep~的结果会非常的多，所以我们需要更加精确的grep。下面是一个例子：

   #+BEGIN_SRC bash
     $ git grep 'Something' -- '*.json' ':(exclude)/xxx' # 在所有*.json（排除/xxx目录下的）中grep搜索'Something'
   #+END_SRC
* 分支管理
** 删除远程分支
   push分支的时候带上~--delete~参数。

   #+BEGIN_SRC bash
   $ git push origin ---delete xxx-branch
   #+END_SRC

* 分支合并
** rebase workflow
   rebase的流程核心的步骤有两步：
   1. 支线分支rebase主分支，保证支线的commmit在排列在主分支之上；
   2. 然后主分支再rebase支线分支，因为支线分支的committ在主分支之上，所以会直接=fast forward=
   
   但是rebase是一种破坏性操作，即你会破坏别人的=base=。所以为了保证“原子性”，实际的操作过程比较多。详见：[[https://randyfay.com/content/rebase-workflow-git][rebase-workflow]].

* tag
** 如何push tag？
   最近在造轮子——“Simple CI”，可以通过Github的WebHook来触发deploy。我希望push一个tag的时候，才进行deploy。

   然后搞了非常久，不知道为什么，"Tag Event"一直都不触发。

   今天才知道，原来我一直没有push tag到服务器，当然不触发了。真是崩溃！！！！！

   =git push= 是不会顺带push tag的，一定要这样： =git push origin tag_name= 才会push tag！！！！
