#+TITLE: [[https://www.coursera.org/learn/learning-how-to-learn][Learn how to learn]]的笔记


* Week 1
** Focused and diffuse modes
   在集中模式跟发散模式直接切换，有利于人的思考。两种模式不能同时存在。

   这点我其实能感受到，但是却从来没有刻意的去做这种模式切换，更多的时候是从一种集中模式的工作切换到另一项集中模式的娱乐事件中去。
** 拖延症
   当你做你很不想做的事情的时候，会痛苦，而大脑会尽量让你避免痛苦。方法就是转移你的注意力，比如娱乐。但研究人员证明，只要你开始做这件事情，这种痛苦其实就很快会消失（我怎么感觉不是所有的事情都能如此？下次多注意观察）。
   视频中提到用番茄闹钟来克服拖延。我觉得这个玩意有时候会不灵，有时候又可以。不灵的表现就是，自己怎么都不愿意去使用。
** 练习是很重要的
   对大部分人而言，数学以及一些科学研究之所以相对比较难，是因为这些科学里面的想过概念在我们身边少有类似的、熟悉的概念出现。对于语言来说，它描述、表达我们日常的所见、所思、所感，所以母语的学习相对容易。

   这说明，在学习那些“不熟悉”的领域，练习其相关的概念跟思想是非常重要的一环。它能加强神经元直接的联系，越是抽象的越需要练习。

   学习一项新东西的时候，先集中经历学习（进入focused mode），然后让自己放松一会，或者转移注意力，进入发散思维模式。在发散思维模式下，大脑在后台**有机会**继续工作，帮助你消化刚才学习的概念。否则就很像填鸭式教育，没办法步步为营，让自己也很累。

** 记忆
   本课只讨论两种记忆系统：长期记忆、工作记忆。这两者类似计算机系统里的硬盘跟寄存器。为什么把工作记忆比作寄存器而不是内存？因为据说大脑的工作记忆模块大概只有4个单元组，是不是很像寄存器？
   长期记忆存储量惊人，但是“读取”需要一点时间，而工作记忆相当于你当前的意识。但是你需要不断的重复，才能避免遗忘掉工作记忆的内容。我们思考问题的时候，经常需要草稿纸来辅助，也是出于这个原因。
   想要把工作记忆转存成长期记忆需要多次的重复记忆。但是，与之前提到的专注模式与发散模式交替进行的学习方法类似，最好是有间隔的重复记忆效果最好，而不是一次性强化记忆很多次，这样的效果很差！

** 睡眠
   睡眠有如下几个作用：
   1. 清除垃圾。清醒时，脑细胞会产生有毒物质；睡眠时，脑细胞缩小，让体液冲刷走有毒物质。长期睡眠不足会导致各种疾病；
   2. 加强重要记忆，清除不重要的记忆。睡眠时，大脑会进行记忆整理。
   3. “梦中排练”复杂问题。尤其在你睡前，你可以暗示自己希望梦到的内容，你可以在梦中的发散思维模式下，继续思考问题。
   4. 释放“意识”区域的资源，让位给其它区域。清醒时的“意识”会占据很多脑部资源，睡眠状态下这部分资源被得意释放。
